top.adapter_path: []
top.booster: flashattn2
top.finetuning_type: lora
top.model_name: Mistral-7B-v0.2-Chat
top.quantization_bit: '8'
top.rope_scaling: none
top.template: mistral
top.visual_inputs: false
train.additional_target: ''
train.badam_mode: layer
train.badam_switch_interval: 50
train.badam_switch_mode: ascending
train.badam_update_ratio: 0.05
train.batch_size: 16
train.compute_type: bf16
train.create_new_adapter: false
train.cutoff_len: 1024
train.dataset:
- docker_NL
train.dataset_dir: data
train.dpo_beta: 0.1
train.dpo_ftx: 0
train.galore_rank: 16
train.galore_scale: 0.25
train.galore_target: all
train.galore_update_interval: 200
train.gradient_accumulation_steps: 4
train.learning_rate: 2e-4
train.logging_steps: 5
train.lora_alpha: 16
train.lora_dropout: 0
train.lora_rank: 8
train.lora_target: ''
train.loraplus_lr_ratio: 0
train.lr_scheduler_type: cosine
train.max_grad_norm: '0.3'
train.max_samples: '100000'
train.name_module_trainable: all
train.neftune_alpha: 0
train.num_layer_trainable: 2
train.num_train_epochs: '1.0'
train.optim: adamw_torch
train.orpo_beta: 0.1
train.packing: false
train.report_to: false
train.resize_vocab: false
train.reward_model: []
train.save_steps: 100
train.shift_attn: false
train.training_stage: Supervised Fine-Tuning
train.upcast_layernorm: false
train.use_badam: false
train.use_dora: false
train.use_galore: false
train.use_llama_pro: false
train.use_rslora: false
train.val_size: 0
train.warmup_steps: 0
